title: Yupana

theme: jekyll-theme-clean-blog

repository: "rusexpertiza-llc/yupana-site"

locale: "ru-RU"

author: Yupana, Первый ОФД
github_username: rusexpertiza-llc
twitter_username: yupanaproject
facebook_username: yupanaproject

defaults:
  values:
    layout: post
    author_profile: false

collections:
  docs:
    output: true
# This will work with Jekyll 4.x
#    sort_by: section

exclude:
  - README
  - vendor
  - Gemfile
  - Dockerfile
